CREATE TABLE FEE_MASTER (
    FEE_ID NUMBER(19) PRIMARY KEY,
    COURSE_ID NUMBER(19),
    REGISTRATION_FEE NUMBER(12,2) NOT NULL,
    TUITION_FEE NUMBER(12,2) NOT NULL,
    EXAM_FEE NUMBER(12,2),
    MATERIAL_FEE NUMBER(12,2),
    TOTAL_FEE NUMBER(12,2) NOT NULL
);

